export default function MethodologyExplainer() {
  return (
    <div className="space-y-10 text-slate-700">
      <section className="space-y-4">
        <p className="text-lg leading-8">
          This calculator uses a transparent economic impact framework grounded in standard input-output analysis. Input-output models estimate how an initial change in economic activity can circulate through a regional economy through direct activity, supplier purchases, and household spending. The calculator applies conservative adjustment factors for local purchasing, net-new activity, commuting leakage, savings, and fiscal capture so that results do not assume that every dollar of project activity remains in the local economy.
        </p>
        <p className="leading-7">
          The calculator estimates the potential direct, indirect, and induced economic effects of a project, expansion, business attraction, retention event, construction project, or operating activity. Results should be interpreted as transparent planning estimates that help users understand scale, assumptions, and uncertainty.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">What The Calculator Estimates</h2>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="font-semibold text-slate-950">Direct Effects</h3>
            <p className="mt-2 text-sm leading-6">The initial jobs, spending, payroll, construction activity, or business operations entered by the user.</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="font-semibold text-slate-950">Indirect Effects</h3>
            <p className="mt-2 text-sm leading-6">Supplier and business-to-business impacts generated by local purchasing and regional supply-chain activity.</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="font-semibold text-slate-950">Induced Effects</h3>
            <p className="mt-2 text-sm leading-6">Household spending impacts generated when workers spend labor income in the local economy.</p>
          </div>
          <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h3 className="font-semibold text-slate-950">Fiscal Estimate</h3>
            <p className="mt-2 text-sm leading-6">An approximate estimate of public revenue effects. It is not a formal audited tax forecast.</p>
          </div>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">Input-Output Foundation</h2>
        <p className="leading-7">
          EconomicImpactCalculator is based on standard input-output economic impact concepts used in public-sector and practitioner tools, including BEA RIMS II, IMPLAN-style regional purchase and leakage concepts, and the input-output framework described by Miller and Blair. The core relationship is commonly expressed as:
        </p>
        <pre className="overflow-auto rounded-xl bg-slate-950 p-5 text-white">x = (I - A)^-1 f</pre>
        <p className="leading-7">
          <strong>x</strong> is total output required, <strong>I</strong> is the identity matrix, <strong>A</strong> is the direct requirements or technical coefficients matrix, <strong>f</strong> is the final demand shock, and <strong>(I - A)^-1</strong> is the Leontief inverse. In practical public analysis, these relationships are adapted to local data, regional purchase behavior, worker residency, and leakage.
        </p>
        <p className="leading-7">
          The calculator uses public county and industry data where available, including BLS QCEW employment and wages, Census County Business Patterns establishments and payroll, ACS demographic and labor-force context, and BEA regional benchmarks. Industry-level output, value-added, labor-income, and multiplier assumptions are documented and adjusted using local employment concentration and regional purchase coefficients.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">Default Assumptions</h2>
        <p className="rounded-xl border border-teal-200 bg-teal-50 p-4 font-medium text-teal-950">
          Default values offer literature-informed, conservative figures. Users should replace these assumptions with project-specific or local data when available.
        </p>
        <p className="leading-7">
          Default values are intended to provide a reasonable starting point when project-specific information is unavailable. They are informed by standard economic impact concepts including local purchase coefficients, regional leakage, household spending effects, additionality, displacement, substitution, and commuting patterns. Users with better project-level information should replace the defaults with verified local spending, payroll, supplier, residency, or tax data.
        </p>
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-50 text-slate-700">
              <tr><th className="p-3">Assumption</th><th className="p-3">How To Interpret It</th></tr>
            </thead>
            <tbody className="align-top">
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Construction duration</td><td className="p-3 leading-6">Temporary construction impacts are treated as one-time activity unless a duration is entered. When duration is provided, construction spending is interpreted over the construction period rather than as permanent annual operations.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Local purchase share</td><td className="p-3 leading-6">Only the locally purchased share of goods and services should generate local supplier impacts. Purchases from vendors outside the study area are treated as leakage.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Net-new share</td><td className="p-3 leading-6">Some activity may not be fully additional because of deadweight, displacement, substitution, or activity that would have occurred anyway. The net-new share adjusts gross impacts to reflect additional local activity.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Commuting leakage</td><td className="p-3 leading-6">Jobs located in a county do not always correspond to workers living in that county. A portion of labor income may leave the study area when workers commute from elsewhere.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Tax rate</td><td className="p-3 leading-6">The fiscal estimate uses a simplified blended assumption. It should not be treated as a formal tax analysis because actual public revenue depends on tax structure, incentives, abatements, residency, and property values.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Savings rate</td><td className="p-3 leading-6">Not all household income is immediately spent locally. Some income is saved, used to pay debt, paid in taxes, invested, or spent outside the region.</td></tr>
              <tr className="border-t border-slate-200"><td className="p-3 font-semibold">Confidence level</td><td className="p-3 leading-6">Confidence ranges reflect variation in assumptions such as local purchasing, net-new share, wages, multipliers, and leakage. Estimates based on verified project data should be interpreted with more confidence than estimates based mostly on defaults.</td></tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">County And Regional Data</h2>
        <p className="leading-7">
          County-level estimates are sensitive to regional boundaries. Smaller geographies usually have higher leakage because more workers, suppliers, and consumer spending cross county borders. A project may be located in one county but draw employees, contractors, customers, and suppliers from a wider labor market.
        </p>
        <p className="leading-7">
          Users should choose the county or region that best matches the real economic geography of the project. If a project affects a broader labor market, users should expand the geography beyond a single county where possible and interpret county-only results as a more localized view of the impact.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">Industry And NAICS Handling</h2>
        <p className="leading-7">
          Industries are identified using North American Industry Classification System codes and displayed in the format <strong>Industry Name (NAICS Code)</strong>. Examples include Pharmaceutical Preparation Manufacturing (325412), Research and Development in Nanotechnology (541713), Research and Development in Biotechnology, except Nanobiotechnology (541714), and Commercial and Institutional Building Construction (236220).
        </p>
        <p className="leading-7">
          NAICS codes allow the calculator to connect user inputs to industry-specific employment, wage, output, and multiplier assumptions where available. Users can search by either industry name or NAICS code.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">Limitations And Appropriate Use</h2>
        <p className="leading-7">
          Results should be interpreted as transparent planning estimates rather than guaranteed outcomes. The calculator is designed to make assumptions visible and adjustable, which is especially important for public-facing economic development analysis.
        </p>
        <ul className="list-disc space-y-2 pl-5 leading-7">
          <li>One job posting does not necessarily equal one job.</li>
          <li>New jobs located in a county do not necessarily mean all workers live in that county.</li>
          <li>Supplier spending may occur outside the county or region.</li>
          <li>Some activity may replace existing local activity rather than being fully net-new.</li>
          <li>Fiscal estimates depend on local tax structures, incentives, abatements, property values, and worker residency.</li>
          <li>Results are sensitive to user-entered assumptions.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-950">References</h2>
        <ul className="space-y-3 text-sm leading-6">
          <li>U.S. Bureau of Economic Analysis. <a className="font-medium text-teal-700" href="https://www.bea.gov/resources/methodologies/RIMSII-user-guide" target="_blank" rel="noreferrer">Regional Input-Output Modeling System (RIMS II) User’s Guide</a>.</li>
          <li>U.S. Bureau of Economic Analysis. <a className="font-medium text-teal-700" href="https://www.bea.gov/system/files/papers/WP2012-3.pdf" target="_blank" rel="noreferrer">Input-Output Models for Impact Analysis: Suggestions for Practitioners Using RIMS II Multipliers</a>.</li>
          <li>Miller, Ronald E., and Peter D. Blair. <em>Input-Output Analysis: Foundations and Extensions</em>. Cambridge University Press.</li>
          <li>IMPLAN. <a className="font-medium text-teal-700" href="https://support.implan.com/hc/en-us/articles/360038706093-Setting-a-Local-Purchase-Percentage-LPP" target="_blank" rel="noreferrer">Setting a Local Purchase Percentage (LPP)</a>.</li>
          <li>IMPLAN. <a className="font-medium text-teal-700" href="https://support.implan.com/hc/en-us/articles/360058533734-Direct-Effect-Leakages" target="_blank" rel="noreferrer">Direct Effect Leakages</a>.</li>
          <li>IMPLAN. <a className="font-medium text-teal-700" href="https://support.implan.com/hc/en-us/articles/360044986833-Regional-Purchase-Coefficients-RPCs" target="_blank" rel="noreferrer">Regional Purchase Coefficients and Local Purchase Percentage methodology documentation</a>.</li>
          <li>Schmit, T.M., Jablonski, B.B.R., and Kay, D. <em>A Practitioner’s Guide to Conducting an Economic Impact Assessment of Regional Food Hubs using IMPLAN</em>.</li>
          <li>Homes and Communities Agency. <a className="font-medium text-teal-700" href="https://assets.publishing.service.gov.uk/media/5a75727340f0b6360e4749f0/additionality_guide_2014_full.pdf" target="_blank" rel="noreferrer">Additionality Guide, Fourth Edition</a>.</li>
          <li>What Works Growth. <a className="font-medium text-teal-700" href="https://whatworksgrowth.org/resource-library/investment-zones-deadweight-and-displacement/" target="_blank" rel="noreferrer">Investment Zones, Deadweight, and Displacement</a>.</li>
          <li>What Works Growth. <a className="font-medium text-teal-700" href="https://whatworksgrowth.org/resource-library/understanding-crowding-out-displacement-and-leakage/" target="_blank" rel="noreferrer">Understanding Crowding Out, Displacement, and Leakage</a>.</li>
        </ul>
      </section>
    </div>
  );
}
